server:
  port: 3031
  ssl:
    enabled: false
  servlet:
    context-path: /api

springdoc:
  paths-to-match: /**
  api-docs:
    path: /swagger-ui/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  nl:
    elstarit:
      reactive: DEBUG

info:
  app:
    name: Event Service API
    version: 1.0.0-SNAPSHOT
    description: Event Service API

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    health.enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics,info,health,prometheus

spring:
  application:
    name: Event Service API
    stub: false
  profiles:
    active: local #@activeProfile@

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/events-store

service:
  cors:
    origins: http://localhost:8080 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/events-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000, http://localhost:4200 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/events-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000, http://localhost:4200 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE

swagger:
  enabled: false
---
